---

name: Coverage

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test-coverage:
    name: Coverage
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:4.0.3

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install dependencies
        run: install.packages("covr", repos="http://cran.rstudio.com/")
        shell: Rscript {0}

      - name: Test coverage
        run: covr::package_coverage()
        shell: Rscript {0}